language: node_js

node_js:
- 10
- 12

matrix:
  include:
  - os: osx
  - os: linux
    compiler: gcc
    env:
      - CXX="g++-4.9"
      - CC="gcc-4.9"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
        - g++-4.9

before_install:
- git submodule update --init --recursive

branches:
  only:
  - master
  - /^v.*$/

deploy:
  provider: script
  script: npm run prebuild && npm run prebuild:upload -u ${PREBUILD_UPLOAD}
  skip_cleanup: true
  on:
    all_branches: true
    tags: true

env:
  global:
    secure: Jn0t44EE07oEY0eUqRAFcbVwf34hAHx6pmWnDHJRBN9XcH3eHo0DFA32TGtbgYy90dChgdKYLWCwbeZzv1nxJiAy/CItCRcfpc4BJAkvxmtoPiFPpkqJl00CRgO+xGselNPgRhdeHeIEYFUcKAzAX7vxB85YTTys3gWV5Zb1SAQ=
